# Generated by Django 4.2.1 on 2023-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_hotdog_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdog',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
